// <auto-generated />
namespace Imenik.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class NaWeb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NaWeb));
        
        string IMigrationMetadata.Id
        {
            get { return "201401192103302_NaWeb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
